### ISSUE TITLE
API Connection Errors

### ISSUE THREAD

**Issue by DXOS3** [riccardoklinger/Hqgis#13]
Here are two of the error reports that I was facing when using the geocoding single address feature. I'm not so sure there is a solid connection with the HERE API yet on my end so this should be smoothed out if possible, 
[Error_Report.txt](https://github.com/riccardoklinger/Hqgis/files/2796148/Error_Report.txt) --> Jan 24
[Error_Report_2.txt](https://github.com/riccardoklinger/Hqgis/files/2796155/Error_Report_2.txt) --> Jan 25--> Inputted to 11 New York for both of them and the second took me to Gottengin, Germany.

**Comment by riccardoklinger** [comment]
Are you connected directly to the web or do you use some fancy proxy? It is mentioned, that the plugin currently uses the requests module and does not care about proxy settings.

**Comment by DXOS3** [comment]
For one thing, you just changed the plugin name so I am currently using v1.3, the latest before it was taken down. I'm not sure if this plugin is supposed to work with any basemap or a certain specifc one but I used a default OSM for a start. I am directly connected to the web here through an ethernet line but web traffic seems to be fine here with little amounts of lag.

**Comment by DXOS3** [comment]
![image](https://user-images.githubusercontent.com/47031119/51748829-9e468a00-207b-11e9-97f4-8de78edecf66.png)

**Comment by riccardoklinger** [comment]
YOu need to replace "YOUR_FANCY_APPID" and "YOUR_FANCY_APPCODE" with the apopid and appcode you received from HERE.

**Comment by DXOS3** [comment]
Oh do you have to have a licence for the API in order to use the plugin? I'm not sure where to find this information.

**Comment by riccardoklinger** [comment]
https://github.com/riccardoklinger/Hqgis#credentials

**Comment by riccardoklinger** [comment]
It is also mentioned in the about-text of the plugin: "Access the HERE API from inside QGIS using your own HERE-API key"

**Comment by DXOS3** [comment]
![image](https://user-images.githubusercontent.com/47031119/52499992-d3d69180-2baa-11e9-9e6b-94f167965c8a.png)
Alright, I'm not that stupid. I'm going to assume that on my end, your geocoder is still not properly connecting to the HERE API, yes even with the saved and loaded credentials on the tab. For information, I have registered a JavaScript AppCode and AppID and the above picture is the result of what came up with the link you sent in post 4.

**Comment by riccardoklinger** [comment]
Javascript AppCode/ID is just working fine on my side. Once again: I don't know about the input you're using, your network settings, etc. I've worked with it from home, on a Mac, WIndows, Linux, in a high speed train, in different netwworks and so on. never saw something wrong there. 
![grafik](https://user-images.githubusercontent.com/7377897/52503156-f6859c00-2be4-11e9-92f3-43d408482621.png)

**Comment by riccardoklinger** [comment]
@DXOS3 please run the plugin again with the python tab opened. Copy the shown messages and paste them here. Furthermore check the creds folder inside the plugin folder. It should contain two files. Waiting for your reply.

**Comment by DXOS3** [comment]
Hi there, I'm not available to try this on the weekend. When I get to work on Monday morning again, I'll give you the onslaught of what I get. including connection settings and the like.

**Comment by DXOS3** [comment]
[New Text Document.txt](https://github.com/riccardoklinger/Hqgis/files/2851232/New.Text.Document.txt)
^Python Message
![image](https://user-images.githubusercontent.com/47031119/52566829-c1da3600-2dd8-11e9-90cd-db61224e17f2.png)
 Network Connection Settings:
-Ethernet
-Connection-specifc DNS Suffix: cihs.ad.gov.on.ca (Maybe causing issues?)
DHCP Enabled: Yes
2 DNS servers and 4 WINS servers.

**Comment by riccardoklinger** [comment]
Sorry for coming back to you this late, Yes, the DNS could be the problem. Are you able to open the URL mentioned in the Python message:
https://geocoder.api.here.com/ ?
Should show something like this:
```
invalid credentials for 
  {
    const open = XMLHttpRequest.prototype.open;
    XMLHttpRequest.prototype.open = function (method, url) {
      open.apply(this, arguments);
      this.addEventListener('readystatechange', function _() {
        if(this.readyState == this.HEADERS_RECEIVED) {
          const contentType = this.getResponseHeader('Content-Type') || '';
          if (contentType.startsWith('video/') || contentType.startsWith('audio/')) {
            window.postMessage({
              source: 'xmlhttprequest-open',
              url,
              mime: contentType,
              method,
              contentType
            }, '*');
          }
          this.removeEventListener('readystatechange', _);
        }
      })
    }
  }
  
```

**Comment by riccardoklinger** [comment]
Oh, seems like this worked before already as you commented. Unfortunately I am a bit lost now.

**Comment by jasoncox35** [comment]
Hello, I am having the same issue with it timing out. The plugin was working fine until Friday and now I cannot do anything with it. Any options for fixing or should I try to find a different way to do what I am doing?

**Comment by riccardoklinger** [comment]
it is still working on my side. will close thise as not reproducible.
