### ISSUE TITLE
POIsearch really works?

### ISSUE THREAD

**Issue by Cecinxs** [riccardoklinger/Hqgis#15]
Hello! I'm making data collect about marketplace, so I'm using POIsearch. Sometimes, the plugin show me the real point, the real location. But, sometimes the plugin show me the wrong point, with names that don't exist.

How could I improve the plugin such that's show me righ place, and the righ name? Does the plugin take the information in google street?

Thank you! (I'm brazilian, so I'm trying to write the better I can, hahaha).

**Comment by riccardoklinger** [comment]
Please describe exactly what categories you're selecting at which location and radius. Furthermore describe your expected result or hwo the result is not matching your expectations.

**Comment by Cecinxs** [comment]
I'm searching for marketplaces, but this categorie doesn't exist. So I put "food and drink" and show me restaurants and marketplaces. There's one big market that the plugin didn't show, one of the most important.  But, majority, it shows me very well.

**Comment by riccardoklinger** [comment]
please send me the coordinates and name for the "big market" you're missing. At  the time being I doubt that this market is already added to the "database" of HERE. Therefore it cannot be found. I am not responsible for the data on HERE. The plugin only offers access to the HERE API.

**Comment by Cecinxs** [comment]
The adress is "Avenida Potirendaba, 3081, Quinta das Paineiras, São José do Rio Preto - SP, 15080-000, Brasil", and the coordinates are "-20.84011,-49.37070". The market calls "Max Atacadista". It bellongs to a large market network calls "Super Muffato", very important to the city. In another adress the "Super Muffato" appears.

**Comment by riccardoklinger** [comment]
THere is only one shopping centere marked in HERE maps at this location which is called Kingcase. check this link:
https://wego.here.com/discover?map=-20.83963,-49.36972,18,normal 

I will close this issue now as I don't see anything plugin related for the time being. If you disagree, please reopen and explain. 
Also you should think about to use the feedback option on the map (Iink see above) to report the missing shopping centre.
