### ISSUE TITLE
Hqgis in model builder

### ISSUE THREAD

**Issue by hoge6b01** [riccardoklinger/Hqgis#17]
I'd like to state an enhancement: would be great to have (some) of the plug-in's features as algorithms that could be excecuted in a processing model chain.

**Comment by riccardoklinger** [comment]
unfortunately I don't have much knowledge in terms of geoprocessing. Definitely looking for support there.

**Comment by riccardoklinger** [comment]
hey @hoge6b01  check the latest commit ca8f097e98a3022f6559da63ef42adf0147b2412 . In v0.4.1 I've added geoprocessing at least for the geocoding of a single field in a txt/point/whatever layer.

**Comment by hoge6b01** [comment]
Excellent! It's working fine.

**Comment by riccardoklinger** [comment]
@hoge6b01
