### ISSUE TITLE
No output from public transport isochrones

### ISSUE THREAD

**Issue by paulbiggwither** [riccardoklinger/Hqgis#22]
I cannot get any output from public transport isochrones (only tried in Sydney) I can see the progress bar flash up but no output appears.
v0.3.4

![image](https://user-images.githubusercontent.com/41716614/52305616-a8587900-29e9-11e9-9df1-291acf6912e3.png)

**Comment by riccardoklinger** [comment]
Isochrones are not supported for public transport. I've removed the option in 0.3.5 74b86dbc19878b2c44eb4c6f4de035d162e4e006 
will close this now
