### ISSUE TITLE
Multiple time banded isochrones

### ISSUE THREAD

**Issue by paulbiggwither** [riccardoklinger/Hqgis#23]
I have successfully created car travel iscochrones, however, if I put in more than one time band no output is returned - again Sydney, but cant see that this would be a geography issue

v0.3.4

**Comment by paulbiggwither** [comment]
I am trying a few different things now, such as your suggestion of bicycle, but that doesn't seem to return any result - pedestrian and car seem to be the only ones working

**Comment by riccardoklinger** [comment]
in which format do you put in the time bands? you should stick to the placeholder: seconds delimited by a comma with no blanks. Can you paste your settings/query so I can debug?

**Comment by riccardoklinger** [comment]
The APi seems not respond to isochrones by bicycle: 
![grafik](https://user-images.githubusercontent.com/7377897/52330375-9bda1d80-29f5-11e9-80a4-fa5348e7e821.png)

**Comment by riccardoklinger** [comment]
removed the option in 0.3.6 / 74b86dbc19878b2c44eb4c6f4de035d162e4e006

**Comment by paulbiggwither** [comment]
apologies was travelling for work - as requested. I thought I tried with no spaces...but maybe I was mistaken. Anyhow I just did it without and it work a treat! Sorry for the hassle - problem in chair... :)

**Comment by riccardoklinger** [comment]
I am closing this for now. If you disagree, please comment and reopen.
