### ISSUE TITLE
Window scaling issues

### ISSUE THREAD

**Issue by tjukanovt** [riccardoklinger/Hqgis#25]
I installed HQgis on my fresh QGIS versions (3.4 LTR & 3.6), but in both the GUI window is scaling in a very weird way, so that the tool becomes unusable. Dragging the window bigger doesn't help as the part with the tools & buttons doesn't scale with it. I am running a Windows 10 and using the (recommended & default) 200% scaling.
![image](https://user-images.githubusercontent.com/13899537/53719824-cc33a100-3e67-11e9-8f8c-f7d00773d78b.png)

**Comment by tjukanovt** [comment]
Almost forgot to mention (sorry I know this makes fixing more difficult), but works on my other laptop just fine... I bet someone else must have the same issue too.

**Comment by riccardoklinger** [comment]
I came across this issue as well on a microsoft surfacebook. Yet I still have no idea on how to solve this.

**Comment by riccardoklinger** [comment]
Sorry for the late merge. Tested it on a normal screen. Can you share some HDPI Screenshots, with before/after change GUI views so I can close this issue? Would be awesome.

**Comment by riccardoklinger** [comment]
or you can close this @tjukanovt

**Comment by tjukanovt** [comment]
@riccardoklinger Not only did I provide you screenshots, but here are animations.

Before:
![hqgis_before](https://user-images.githubusercontent.com/13899537/62756027-e7da4d80-ba7e-11e9-9fbb-b1dcfd6602e6.gif)

After:
![hqgis_after](https://user-images.githubusercontent.com/13899537/62756110-2bcd5280-ba7f-11e9-8688-a5610361ec74.gif)
