### ISSUE TITLE
Points id on Isochrones

### ISSUE THREAD

**Issue by AngelNieves** [riccardoklinger/Hqgis#37]
Hi Riccardo, I just installed your plugin and I think that is a very good tool. The only problem that I found is when you run the isochrones calculator for multiple addresses the tool doesn't save an id or somenthing to link the starts shapefile and the isochrones shapefile.

**Comment by riccardoklinger** [comment]
thanks for the enhancement wish. I will try to incoprorate this as soon as I  have the time to.

**Comment by riccardoklinger** [comment]
closing as no response so far. please reopen if needed.
