### ISSUE TITLE
Trouble geocoding addresses

### ISSUE THREAD

**Issue by anderfideles** [riccardoklinger/Hqgis#38]
Hello Riccardo, 

I am not able to geocode an address as a batch. Do you have any tip? I already added the Here API as per the information in Github. An error message appears as shown below:

![img](https://user-images.githubusercontent.com/48888592/68093976-5e1dfe80-fe7a-11e9-9abf-cff9b10c7a14.jpg)

Regards,
Anderson

**Comment by riccardoklinger** [comment]
Hi Anderson, 
sorry for getting into this so late. have you found a solution on this already?

Best, RIccardo

**Comment by bocosrs** [comment]
Same here using QGIS 3.10 and 3.12, Sure you're also aware of the changes to Here API Codes.

**Comment by riccardoklinger** [comment]
I've pushed a new branch to this repo which sues the new API key redentials and new API endpoints. Yet it seems, that Places API is not available for testing right now and only supports old app-id / code credentials. will work on this later on. routing, geiocoding and isolines should work here: 1b5374d
Yet it seems that everything should be ported to
"Geocoding and Search API v7"

**Comment by riccardoklinger** [comment]
@bocosrs have you had the chance to test the branch?!

**Comment by riccardoklinger** [comment]
should be fixed now and new plugin was released in 20a62f451d94a6daf3498479643d7f976ca1db37

**Comment by riccardoklinger** [comment]
closing this now. if needed open, please comment.
