### ISSUE TITLE
HERE no longer produces App Code

### ISSUE THREAD

**Issue by jamgreen** [riccardoklinger/Hqgis#39]
HERE has deprecated the use of APP-codes as documented [here](https://developer.here.com/documentation/authentication/dev_guide/topics/app-credentials.html).

They now only offer API keys. Unclear if this ultimately harms the plugins performance, but, at minimum should update the documentation.

**Comment by riccardoklinger** [comment]
yes, you're right. I might change this if I do have the time to do so. Thank you for reporting in.

**Comment by riccardoklinger** [comment]
I've pushed a new branch to this repo wihich sues the new API key redentials and new API endpoints. Yet it seems, that Places API is not available for testing riught now and only supports old app-id / code credentials. will work on this later on. routing, geiocoding and isolines should work here: 1b5374d
Yet it seems that everything should be ported to
"Geocoding and Search API v7"

**Comment by riccardoklinger** [comment]
fixed and solved in 20a62f451d94a6daf3498479643d7f976ca1db37
