### ISSUE TITLE
Cannot Load Plugin

### ISSUE THREAD

**Issue by gnh632** [riccardoklinger/Hqgis#41]
Downloaded the zipped file, and tried to install from zip. Is this a python version issue?

2020-02-19T20:24:04     WARNING    Python error : Couldn't load plugin 'Hqgis-master' due to an error when calling its classFactory() method See message log (Python Error) for more details.

![image](https://user-images.githubusercontent.com/44662734/74898801-38006980-5358-11ea-8a2b-8a4dc20d7975.png)

**Comment by riccardoklinger** [comment]
tried it today with Mac, 

QGIS version | 3.4.15-Madeira
and everything works fine.

**Comment by gnh632** [comment]
I grabbed a different download, and got it to work.  
Thanks!
    On Thursday, February 20, 2020, 09:02:38 AM MST, Riccardo Klinger <notifications@github.com> wrote:  
 
 
tried it today with Mac,

QGIS version | 3.4.15-Madeira
and everything works fine.
