### ISSUE TITLE
Plugin does not respond

### ISSUE THREAD

**Issue by HalukaMB** [riccardoklinger/Hqgis#42]
Hey there, first of all thanks for going to the lengths of creating this plugin. I was just wondering whether due to the fact of changing from App keys to API keys the plugin is not working anymore. I have just installed the plugin but seemingly it cannot communicate with HERE, because when I click on the button, nothing happens. Are you aware of any issues regarding connectivity?

**EDIT:** So from first small digs into the code, I think the main issue is that the authentication model at HERE was changed from App ID, App Code to App ID, ApiKey. Also the url structure has changed from e.g. "https://geocoder.api.here.com/6.2/geocode.json" to "https://geocoder.ls.hereapi.com/6.2/geocode.json". I couldn't write a full fledged fix for now but would be great to collaborate on one.

**Comment by riccardoklinger** [comment]
This is definitely not an issue of the api keys in my point of view. Yes, you're right, we need  a port to the new API. but as said, worked today ith a fresh install, saved my appid and code, single record geocode was no issue.

**Comment by riccardoklinger** [comment]
I've pushed a new branch to this repo wihich sues the new API key redentials and new API endpoints. Yet it seems, that Places API is not available for testing riught now and only supports old app-id / code credentials. will work on this later on. routing, geiocoding and isolines should work here: 1b5374d693ccbd51f0702ec3003bd15e1f7a1b4e 
Yet it seems that everything should be ported to 
"Geocoding and Search API v7"

**Comment by riccardoklinger** [comment]
@HalukaMB have you tested the new branch?

**Comment by HalukaMB** [comment]
Not yet, apologies. I am a bit consumed by the current news events. But will asap.

**Comment by riccardoklinger** [comment]
I have released a new version for the new API. it is waiting for aproval in the plugin repo of qgis.

**Comment by riccardoklinger** [comment]
closing, pleas reopen if needed
