### ISSUE TITLE
Plug-in does not work

### ISSUE THREAD

**Issue by mvremolador** [riccardoklinger/Hqgis#43]
Hi,

I downloaded HQGIS 0.4.4 plug-in and successfully installed it in QGIS. I also created the credential from HERE site and was able to generate APP ID and API Key. Is API key different from API code? I tried to do geocoding of a single address but it does not work. It would mean a lot if you could help me on this. I don't know anything about coding so I'm just depending on the plug-in tool. My purpose in using this plug-in is to do isochrone analysis of 111 points in the Philippines and I need to consider the traffic which the plug-in can provide. Again thank you so much for this helpful tool.

**Comment by riccardoklinger** [comment]
Hi @mvremolador . I am working on a new branch as the API changed and only uses apikey authentication right now. goecoding and isochrones should work just fine on the apikey branch. are you able to download this branch and test it? Iyou should also use QGIS 3.10 or 3.4. Have not checked it with QGIS 3.12 yet and there are people who saw some issues with 3.12

**Comment by mvremolador** [comment]
Hi! Thank you for the prompt response. Where can I download this branch? By the way, does the road data covers the Philippines?

**Comment by riccardoklinger** [comment]
here you go: https://github.com/riccardoklinger/Hqgis/tree/apikey and philipines should be supported.

**Comment by riccardoklinger** [comment]
it is already in master and in the official repo now. please update and report back. will close this for now. if needed to be reopened, report back

**Comment by mvremolador** [comment]
Hi! I already tried installing the new version but I encountered this error.

![Capture](https://user-images.githubusercontent.com/36612903/77811841-30ab4900-70d8-11ea-9279-dee5a3a3ed6d.JPG)

I am using QGIS 3.10.3 version. I did the usual install from zip. I am not sure if i did anything wrong.

Thank you very much!

**Comment by riccardoklinger** [comment]
I’ve uploaded the same branch already to the official repo of plugins for QGIS. So you can install it the normal way.
If you check the error you will see that it was installed in a folder name like Hqgis-apikey or different. Rename this folder to Hqgis and you should be fine or install the plugin via the normal plugin download and install process in the plugin manager.



Von meinem iPhone gesendet

**Comment by mvremolador** [comment]
Hi! It already works now. Thank you very much!

**Comment by mvremolador** [comment]
Hi! I tried enabling traffic and specified a date and time when I want to do the isochrone analysis. Given that the point of origin is in the Philippines, does it automatically adapts Philippine time zone for the traffic information?

Again, thank you so much. You're tool is very helpful!

**Comment by mvremolador** [comment]
Also, I an just curious as to how HERE API accounts for the traffic or what historical traffic data they use? Since we can generate isochrone analysis even for past dates.
