### ISSUE TITLE
isochroneBatch from a MultiPoint Layer

### ISSUE THREAD

**Issue by Niarolf** [riccardoklinger/Hqgis#58]
Hi,
actually it seems that the getIsochronesBatch accept only a QgsPoint Layer but not QgsMultiPoint.
If it's a MultiPoint you take an error on line 1268 if the layer is not in 4326 or on line 1272 in 4326.
So originFeatures must be a QgsPoint geometry.
Will you add a test for tell the user and a workflow for a QgsMultipoint layer source ?
So it's a great job that you are doing !!!
Thanks a lot
Niarolf

**Comment by riccardoklinger** [comment]
hi @Niarolf . thanks for raising this. The main problem with QgsMultipoints: If there is a true multipoint, than there are multiply xy-coordinate pairs per "feature". Do you have a suggestion on how to deal with theses multiple inputs for isochrone calcualtion ? Should there be an isochrone for each xy-pair or an isochrone for the center of the multipoint? But I'll alter the plugin to allow only QgsPoint Layer.

**Comment by riccardoklinger** [comment]
The definition of the input can only be limitd to "PointLayer":
self.dlg.IsoAddressBatch.setFilters(QgsMapLayerProxyModel.PointLayer) (see here. https://qgis.org/pyqgis/3.0/core/Map/QgsMapLayerProxyModel.html#qgis.core.QgsMapLayerProxyModel.PointLayer) But I will add a warning if the layer is MultiPoint

**Comment by riccardoklinger** [comment]
The original error with multipoints is: 

`MultiPoint geometry cannot be converted to a point. Only Point types are permitted.`

**Comment by riccardoklinger** [comment]
fixed in master. will update the qgis repo soon.
