### ISSUE TITLE
Isochrone layer result: where can I find the parameters

### ISSUE THREAD

**Issue by guibar** [riccardoklinger/Hqgis#61]
Hello,
Thanks for your work which is very useful. 
When I run the plugin to get isochrones, I get a layer called isoLayer but I can't find anywhere in the definition of that layer the parameters I have used to generate it. Are they stored somewhere?

Thanks a lot,

Guillaume

**Comment by briet** [comment]
they are stored in the attribute table

**Comment by guibar** [comment]
Hi briet and thanks for your help.
I can see all of them in the attributes table but not the origin point. Can it be found somewhere?
Thanks again.

**Comment by gwezerek** [comment]
Agree that this would be a nice. If it helps others: I was able to add the feature I wanted from the input layer by downloading the zipped module, modifying the relevant function in hqgis.py and then installing hqgis from zip in the qgis plugins manager.

**Comment by zhangyixinSarah** [comment]
dear guibar, I can not generate isochrones. I want to generate isochrones of 100 points in the QGIS3.2. I Generated the API Key and followed the instructions and online tutorials, but nothing works. Clicking on "save credentials" I get the message "credentials saved to QGIS Global Settings", there is no file called credentials.json in my computer. thanks.

**Comment by riccardoklinger** [comment]
@guibar : the resulting layer will have a column called origin_fid which maps to the original ids in the source layer with your 100 points.
