### ISSUE TITLE
TOS / Usage

### ISSUE THREAD

**Issue by thbaumann** [riccardoklinger/Hqgis#63]
Hi Riccardo,
I really like the batch geocoding-functionality but I am not sure if the "normal"(freemium) users of this plugin are allowed to use the HERE services in combination with this plugin:

https://legal.here.com/en-gb/terms/acceptable-use-policy 

```
"Unless otherwise permitted in your commercial agreement with HERE, HERE Properties may not be used 
in connection with any of the following:

    - ...
    - GIS (geographic information systems) applications, such as applications that analyze, process or visualize (or any combination of them) information in order to manage land use, natural resources, environment, urban or enterprise facilities, communications or utility networks or any other fixed assets "
```

regards,
Thomas

**Comment by riccardoklinger** [comment]
The TOS  you were hotlinking seems to be outdated. I cannot find the section in the updated one:
https://legal.here.com/en-gb/terms/acceptable-use-policy-2019 (Effective date: 01/12/2019)
https://legal.here.com/en-gb/terms/acceptable-use-policy (Effective date: 04/06/2018)

**Comment by thbaumann** [comment]
nice :-)
This up to date acceptable-use-policy is a bit hidden.
I followed the link which was hotlinked in the readme.md in this repository but even at the TOS overview page at HERE ( https://legal.here.com/en-gb/terms/terms-for-here-products-and-services ) the old acceptable-use-policy is hotlinked.
Thanks for clarifying this.
