### ISSUE TITLE
version 1.1.1 contains

### ISSUE THREAD

**Issue by thbaumann** [riccardoklinger/Hqgis#64]
Hi Riccardo,
Version 1.1.1 in the official QGIS repository (https://plugins.qgis.org/plugins/Hqgis/version/1.1.1/)
contains a "_MACOSX" folder which causes trouble in the plugin installer:

![grafik](https://user-images.githubusercontent.com/20082727/102181474-ec9ce600-3eaa-11eb-96aa-569b2fc20642.png)

regards,
Thomas

**Comment by riccardoklinger** [comment]
fixed in 1.2.0
