### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by tveinot** [riccardoklinger/Hqgis#72]
When I run isochrones I get this error

Traceback (most recent call last):
  File "C:/Users/tveinot/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Hqgis\hqgis.py", line 844, in geocodeline
    self.appId + "&searchtext=" + address
TypeError: can only concatenate str (not "NoneType") to str

I get this with or without an address.

**Comment by riccardoklinger** [comment]
can you check with the new version 1.2.0 available in plugin manager?

**Comment by riccardoklinger** [comment]
closing this issue as no response was given.
