### ISSUE TITLE
Plugin seems don't work

### ISSUE THREAD

**Issue by opalina79** [riccardoklinger/Hqgis#74]
Hi, I installed the plugin on QGIS 3.30.1. I created an API Key on the HERE site and fill in the generated API Key in the credentials-tab of the plugin. Clicking on "save credentials" I get the message "credentials saved to QGIS Global Settings", but then, trying the various tools, nothing seems to work.
Can you tell me if it's a compatibility problem or could there be other reasons? Thank you
Cinzia

**Comment by joaopmoniz** [comment]
I am having the same issue. Generated the API Key and follow instructions and online tutorials, but nothing works.

**Comment by zhangyixinSarah** [comment]
I am having the same issue. Generated the API Key and followed the instructions and online tutorials, but nothing works.  Clicking on "save credentials" I get the message "credentials saved to QGIS Global Settings", there is no file called credentials.json in my computer. thanks.

**Comment by ArneRehmann** [comment]
I`m having the same issue as zhangyixinSarah and opalina79. I . But I´m not 100% sure I´f I do a mistake or if the plug in is not working properly.

**Comment by riccardoklinger** [comment]
Arne, download the branch version2 as a zip and install it (rmeove the
-master in the name in the zip and containing folders first, prior
installation) it should work a bit better. In the past I hadn't such a high
motivation to keep this plugin under maintenance.
______________________________________
"The best model for a cat is another, or preferably the same cat."

**Comment by ArneRehmann** [comment]
Hi Riccardo, thank you very much for the promt answer. I downloaded the branch version 2, by selcting the branch version2 here at github. However I could not find a file/folder with the "master" in the name.

Installing the zip without any change was leading to the following error:

Konnte Erweiterung 'Hqgis-version2' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 

ModuleNotFoundError: No module named 'Hqgis' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.11/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/00012732/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Hqgis-version2\__init__.py", line 35, in classFactory
    from .hqgis import Hqgis
  File "C:\PROGRA~1/QGIS32~1.11/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/00012732/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Hqgis-version2\hqgis.py", line 64, in 
    from Hqgis.HqgisProvider import HqgisProvider
  File "C:\PROGRA~1/QGIS32~1.11/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'Hqgis'


What am I doing wrong?

**Comment by riccardoklinger** [comment]
Check your linkedin Von meinem iPhone gesendetAm 06.10.2023 um 09:52 schrieb ArneRehmann ***@***.***>:﻿
Hi Riccardo, thank you very much for the promt answer. I downloaded the branch version 2, by selcting the branch version2 here at github. However I could not find a file/folder with the "master" in the name.
Installing the zip without any change was leading to the following error:
Konnte Erweiterung 'Hqgis-version2' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode
ModuleNotFoundError: No module named 'Hqgis'
Traceback (most recent call last):
File "C:\PROGRA1/QGIS321.11/apps/qgis-ltr/./python\qgis\utils.py", line 423, in startPlugin
plugins[packageName] = package.classFactory(iface)
File "C:\Users/00012732/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Hqgis-version2_init.py", line 35, in classFactory
from .hqgis import Hqgis
File "C:\PROGRA1/QGIS321.11/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
File "C:\Users/00012732/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Hqgis-version2\hqgis.py", line 64, in
from Hqgis.HqgisProvider import HqgisProvider
File "C:\PROGRA1/QGIS321.11/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'Hqgis'
What am I doing wrong?

**Comment by riccardoklinger** [comment]
@opalina79 , @joaopmoniz @zhangyixinSarah I think, I fixed it. Please reload it via qgis plugin manager
