### ISSUE TITLE
pedestrian road speed

### ISSUE THREAD

**Issue by vsmstq** [riccardoklinger/Hqgis#78]
Hi! It is very useful and easy to use. I just like to ask what is the pedestrian road speed does it use? Thanks,

**Comment by riccardoklinger** [comment]
#letMeGoogleThatForYou: https://www.here.com/learn/blog/pedestrian-routing-with-here-routing-api 

Transport Mode: Pedestrian

To use pedestrian routing, set transportMode=pedestrian. The default speed is 1 meter per second / 3.6 kilometers per hour / 2.23 miles per hour. Or the running or hiking speed equivalent, it is 26.8 minutes per mile or 16.67 minutes per kilometer. Below is the sample request using the default speed. Refer to this [tutorial](https://developer.here.com/documentation/routing-api/dev_guide/topics/use-cases/pedestrian-default.html) for more information.
