### ISSUE TITLE
hqgis not working

### ISSUE THREAD

**Issue by cesarVHE** [riccardoklinger/Hqgis#79]
hello!

I need to use hqgis in qgis 3.30.3-'s-Hertogenbosch, I installed the latest plugin 1.2, I registered to get credentials, I followed all the tutorials and videos... and none of the modules work, can you help me?

**Comment by riccardoklinger** [comment]
Have you seen any errors? Can you provide a sample dataset?

**Comment by cesarVHE** [comment]
Yes, I am working with qgis 3.30.3-'s-Hertogenbosch, I downloaded hqgis 1.2 from your github, installed and obtained the credentials from the page... in the isochrons tab I put the point on the qgis data frame (it does not recognize the address but if it gives the coordinates) somewhere in Mexico City (I also tried with several points in Mexico), I assign parameters: start, time (300, 600, 900 seconds), try fast and short, try all the travel modes (car, bicycle...), I tried with traffic activated (with different dates and times) and deactivated... and when I click on the calculate isochrones button nothing happens
![Captura](https://github.com/riccardoklinger/Hqgis/assets/71098892/5f6d4574-cd31-4578-a94b-8015236451a1)

**Comment by riccardoklinger** [comment]
Please remove the image with your personal api key. I will download 3.30 and will post / try an example in Mexico City.Von meinem iPhone gesendetAm 13.11.2023 um 16:41 schrieb cesarVHE ***@***.***>:﻿
Yes, I am working with qgis 3.30.3-'s-Hertogenbosch, I downloaded hqgis 1.2 from your github, installed and obtained the credentials from the page... in the isochrons tab I put the point on the qgis data frame (it does not recognize the address but if it gives the coordinates) somewhere in Mexico City (I also tried with several points in Mexico), I assign parameters: start, time (300, 600, 900 seconds), try fast and short, try all the travel modes (car, bicycle...), I tried with traffic activated (with different dates and times) and deactivated... and when I click on the calculate isochrones button nothing happens

**Comment by cesarVHE** [comment]
Meanwhile, could you tell me in which versions the plugin works well?

**Comment by riccardoklinger** [comment]
All tests were done in 3.28Von meinem iPhone gesendetAm 13.11.2023 um 21:02 schrieb cesarVHE ***@***.***>:﻿
Meanwhile, could you tell me in which versions the plugin works well?

**Comment by riccardoklinger** [comment]
<img width="1525" alt="grafik" src="https://github.com/riccardoklinger/Hqgis/assets/7377897/2a824dd0-5d6d-4471-b32a-0f686e4e8053">
works fine in QGIS 3.32 as well

**Comment by riccardoklinger** [comment]
For a check: 
please open the plugin, switch to tab "geocode", paste the following address: "Filósofos 85, Jardines de Churubusco, 09410 Iztapalapa, CMX, Mexico" and press "Geocode Single Address" . 
The result should be a layer with a single feature.
I also saw your API key. This looked a bit short to me, so please check again in developer.here.com whether you've copied the right key. Maybe my documentation is a bit outdated.

![Screenshot 2023-11-13 at 22-09-11 Project Page - HERE Developer](https://github.com/riccardoklinger/Hqgis/assets/7377897/f52a1574-786e-4182-b6b7-bff66c64d361)

You should take the REST API key as highlighted in the image above.

**Comment by cesarVHE** [comment]
The screen where I get the key is this one, I think it is shorter
![Captura](https://github.com/riccardoklinger/Hqgis/assets/71098892/293797a3-be8b-4ecf-92b5-829351b36e61)
![Captura_2](https://github.com/riccardoklinger/Hqgis/assets/71098892/b6c355af-ca89-4fa4-93ba-f94e0ac955bf)

I did the test in the geocoding window, how long does it take? apparently it doesn't do anything... I tried putting the address in the isochron window and with the cursor over the data frame but it doesn't do anything either

**Comment by cesarVHE** [comment]
ready! It was a problem with my api key, I really appreciate your support
![Captura](https://github.com/riccardoklinger/Hqgis/assets/71098892/a0eaa727-84c1-41b4-83f3-0fafab26a4ed)

**Comment by riccardoklinger** [comment]
@cesarVHE I am closing this issue then. If you like my plugin, maybe check the sponsoring tab: https://github.com/sponsors/riccardoklinger
