### ISSUE TITLE
Distance Isochrones results

### ISSUE THREAD

**Issue by paulbiggwither** [riccardoklinger/Hqgis#80]
Hi there,

love the tool btw, however this time when I started using it I noticed that the distance isochrones returned seemed off, maybe? 
I ran some tests 2,200,2000 and the distance seem all out...with 200 perhaps being closest to the 2000m I was expecting...unless in my absence from using the tool I hjave forgotten some crucial thing!

cheers

Paul 

![hqgis settings](https://github.com/riccardoklinger/Hqgis/assets/41716614/5e26da16-e0f0-4197-9dfd-4f1f042201ec)
![measure1](https://github.com/riccardoklinger/Hqgis/assets/41716614/ad2ced2f-71ba-4e42-96f7-70c15fb2f690)

**Comment by riccardoklinger** [comment]
Hi Paul, Let me check that with the same settings.Best, RiccardoVon meinem iPhone gesendetAm 14.11.2023 um 10:09 schrieb paulbiggwither ***@***.***>:﻿
Hi there,
love the tool btw, however this time when I started using it I noticed that the distance isochrones returned seemed off, maybe?
I ran some tests 2,200,2000 and the distance seem all out...with 200 perhaps being closest to the 2000m I was expecting...unless in my absence from using the tool I hjave forgotten some crucial thing!
cheers
Paul

**Comment by riccardoklinger** [comment]
Yes, you're right. I was able to reproduce the error. If you need a solution fast, use the processing equivalent in the processing tools:
<img width="1800" alt="grafik" src="https://github.com/riccardoklinger/Hqgis/assets/7377897/2d58f33a-f12e-4499-8734-254df0ee5c5f">

**Comment by riccardoklinger** [comment]
new version released, waiting for approval.

**Comment by paulbiggwither** [comment]
awesome, (glad it wasnt a me problem!) will check it out! didnt even think to try processing equivalent
Thanks Riccardo!
cheers
Paul

**Comment by riccardoklinger** [comment]
@paulbiggwither I am closing this issue then. If you like my plugin, maybe check the sponsoring tab: https://github.com/sponsors/riccardoklinger
